### ISSUE TITLE
Erreurs de packet Imagenex

### ISSUE THREAD

**Issue by hugoeeb** [CIDCO-dev/Imagenex852#11]
Dans quelque fichiers .852, les fins de packet ne son pas correct.

La fin d'un packet normal devrait être: 
FC suivie de 19 bytes 0 (zéro)

Mais dans les packet pas correct, c'est:
FC suivie de 20 bytes 0 (zéro)

**Comment by glabmoris** [comment]
C'est un cas qui arrive et qui est hors de notre contrôle. J'ai corrigé le parser pour qu'il gère ces cas plus gracieusement.
