### ISSUE TITLE
Reintegrer Dump852 à Jenkins

### ISSUE THREAD

**Issue by glabmoris** [CIDCO-dev/Imagenex852#13]
Le projet QT Dump852 était mal placé dans l'arborescence du repo. Je l'ai déplacé à la bonne place mais ça brise Jenkins

**Comment by hugoeeb** [comment]
Donne moi des bon path et je vais le réparer ASAP

**Comment by glabmoris** [comment]
rename {Dump852 => src/examples/Dump852}

**Comment by hugoeeb** [comment]
La pipeline est de nouveau fonctionnelle.
