### ISSUE TITLE
Intégrer à Jenkins

### ISSUE THREAD

**Issue by glabmoris** [CIDCO-dev/Imagenex852#4]
Intégrer à Jenkins pour compilation sur Windows et Linux

**Comment by glabmoris** [comment]
@HugoValcourt Est-ce que les éxécutables Windows sont mis en ligne sur le serveur apache?

**Comment by hugoeeb** [comment]
Il sont mit en ligne sur 192.168.0.105. Qu'est-ce que tu veux dire par apache? Archiva?

**Comment by glabmoris** [comment]
Non, le directory sur 192.168.0.105

**Comment by glabmoris** [comment]
Il faut ajouter aussi le GUI fait par @EmileGagne  dans le folder Dump852 au build pour produire des executables Windows
